server:
  port: 8800

spring:
  application:
    name: config
  cloud:
    config:
      label:
      server:
        git:
          uri:
          search-paths:
          username: 576386273@qq.com
          password: h19910918

eureka:
  client:
    service-url:
      defaultZone: http://admin:123@localhost:8761/eureka/