server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://119.23.52.245:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: test
    password: test!@#$
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  global-config:
    db-config:
      id-type: auto

logging:  level:    com.demo.mybatisplus.mapper: debug











